apps/composition/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import CollectionDetailView, CollectionDetailEmbedView, EarnerPortal

urlpatterns = patterns('earner.views',
    url(r'^/collections/(?P<pk>[^/]+)/(?P<share_hash>[^/]+)$', CollectionDetailView.as_view(), name='shared_collection'),
    url(r'^/collections/(?P<pk>[^/]+)/(?P<share_hash>[^/]+)/embed$', CollectionDetailEmbedView.as_view(), name='shared_collection_embed'),
    url(r'^', login_required(EarnerPortal.as_view()), name='earner_portal'),
)

apps/health/urls.py
from django.conf.urls import patterns, url
from views import health

urlpatterns = patterns('contact.views',
    url(r'^$', health, name='server_health'),
)

apps/mainsite/urls.py
from django.apps import apps
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from .views import SitemapView, info_view, email_unsubscribe

from mainsite.admin import badgr_admin
badgr_admin.autodiscover()
# make sure that any view/model/form imports occur AFTER admin.autodiscover

TOKEN_REGEX = '(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})'

sitemaps = {
}

urlpatterns = patterns('',
    # Backup URLs in case the server isn't serving these directly
    url(r'^favicon\.png[/]?$', RedirectView.as_view(url='%simages/favicon.png' % settings.STATIC_URL)),
    url(r'^favicon\.ico[/]?$', RedirectView.as_view(url='%simages/favicon.png' % settings.STATIC_URL)),
    url(r'^robots\.txt$', RedirectView.as_view(url='%srobots.txt' % settings.STATIC_URL)),

    # Home
    url(r'^$', info_view, name='index'),

    # Sitemaps
    url(r'^sitemap$', SitemapView.as_view(), name='sitemap'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Admin URLs
    url(r'^staff/', include(badgr_admin.urls)),

    # accounts:
    url(r'^accounts[/]?$', RedirectView.as_view(url='/accounts/email/')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^unsubscribe/(?P<email_encoded>[^/]+)/(?P<expiration>[^/]+)/(?P<signature>[^/]+)', email_unsubscribe, name='unsubscribe'),
    url(r'^login', RedirectView.as_view(url='/accounts/login', permanent=False, query_string=True), name='login'),
    url(r'^logout', RedirectView.as_view(url='/accounts/logout', permanent=False), name='logout'),

    # REST Framework-based APIs
    url(r'^user', include('badgeuser.urls')),
    url(r'^v1/user', include('badgeuser.api_urls')),
    url(r'^api-auth/token$', obtain_auth_token),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^public', include('issuer.public_api_urls')),

    url(r'^docs/', include('rest_framework_swagger.urls')),

    # Service health endpoint
    url(r'^health', include('health.urls')),

    # JSON-LD Context
    url(r'^json-ld/', include('badgrlog.urls')),

)

if apps.is_installed('issuer'):
    urlpatterns += patterns('',
        url(r'^v1/$', RedirectView.as_view(url='/v1/issuer/issuers', permanent=False)),
        url(r'^v1/issuer', include('issuer.api_urls')),
        url(r'^issuer', include('issuer.urls')),
    )

if apps.is_installed('composition'):
    urlpatterns += patterns('',
        url(r'^v1/earner', include('composition.api_urls')),
        url(r'^earner', include('composition.urls')),
    )

if apps.is_installed('badgebook'):
    urlpatterns += patterns('',
        url(r'^v1/badgebook', include('badgebook.api_urls')),
        url(r'^badgebook', include('badgebook.urls')),
    )


handler404 = 'mainsite.views.error404'
handler500 = 'mainsite.views.error500'
# Test URLs to allow you to see these pages while DEBUG is True
if getattr(settings, 'DEBUG_ERRORS', False):
    urlpatterns = patterns('mainsite.views',
        url(r'^error/404/$', 'error404', name='404'),
        url(r'^error/500/$', 'error500', name='500'),
    ) + urlpatterns

# If DEBUG_MEDIA is set, have django serve anything in MEDIA_ROOT at MEDIA_URL
if getattr(settings, 'DEBUG_MEDIA', True):
    media_url = getattr(settings, 'MEDIA_URL', '/media/').lstrip('/')
    urlpatterns = patterns('',
        url(r'^%s(?P<path>.*)$' % (media_url,), 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT
        }),
    ) + urlpatterns

# If DEBUG_STATIC is set, have django serve up static files even if DEBUG=False
if getattr(settings, 'DEBUG_STATIC', True):
    static_url = getattr(settings, 'STATIC_URL', '/static/').lstrip('/')
    urlpatterns = patterns('',
        url(r'^%s(?P<path>.*)' % (static_url,), 'django.contrib.staticfiles.views.serve', kwargs={
            'insecure': True,
        })
    ) + urlpatterns

# Serve pattern library view only in debug mode or if explicitly declared
if getattr(settings, 'DEBUG', True) or getattr(settings, 'SERVE_PATTERN_LIBRARY', False):
    urlpatterns = patterns('',
       url(r'^component-library$', TemplateView.as_view(template_name='component-library.html'), name='component-library')
    ) + urlpatterns

apps/composition/models.py
from django.db import models
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.urlresolvers import reverse

from autoslug import AutoSlugField
import cachemodel

from mainsite.models import (AbstractIssuer, AbstractBadgeClass,
                             AbstractBadgeInstance)

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class LocalIssuer(AbstractIssuer):
    pass


class LocalBadgeClass(AbstractBadgeClass):
    issuer = models.ForeignKey(LocalIssuer, blank=False, null=False,
                               on_delete=models.PROTECT,
                               related_name="badgeclasses")

    class Meta:
        verbose_name = 'local badge class'
        verbose_name_plural = 'local badge classes'


class LocalBadgeInstance(AbstractBadgeInstance):
    # 0.5 BadgeInstances have no notion of a BadgeClass
    badgeclass = models.ForeignKey(LocalBadgeClass, blank=False, null=True,
                                   on_delete=models.PROTECT,
                                   related_name='badgeinstances')
    # 0.5 BadgeInstances have no notion of a BadgeClass
    issuer = models.ForeignKey(LocalIssuer, blank=False, null=True)

    recipient_user = models.ForeignKey(AUTH_USER_MODEL)

    def image_url(self):
        if getattr(settings, 'MEDIA_URL').startswith('http'):
            return default_storage.url(self.image.name)
        else:
            return getattr(settings, 'HTTP_ORIGIN') + default_storage.url(self.image.name)


class Collection(cachemodel.CacheModel):
    name = models.CharField(max_length=128)
    slug = AutoSlugField(max_length=128, populate_from='name', blank=False,
                         editable=True)
    description = models.CharField(max_length=255, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=False)
    share_hash = models.CharField(max_length=255, null=False, blank=True)

    instances = models.ManyToManyField(LocalBadgeInstance,
                                       through='LocalBadgeInstanceCollection')
    shared_with = models.ManyToManyField(AUTH_USER_MODEL,
                                         through='CollectionPermission',
                                         related_name='shared_with_me')

    class Meta:
        unique_together = ('owner', 'slug')

    @property
    def share_url(self):
        if self.share_hash != '':
            return getattr(settings, 'HTTP_ORIGIN') + reverse(
                'shared_collection', args=[self.pk, self.share_hash])
        return ''


class LocalBadgeInstanceCollection(models.Model):
    instance = models.ForeignKey(LocalBadgeInstance, null=False)
    collection = models.ForeignKey(Collection, null=False)

    description = models.TextField(blank=True)

    class Meta:
        unique_together = ('instance', 'collection')
        verbose_name = "BadgeInstance in a Collection"
        verbose_name_plural = "BadgeInstances in Collections"

    def __unicode__(self):
        return u'{} in {}\'s {}'.format(
            self.instance.badgeclass.name,
            self.instance.recipient_user.username,
            self.collection.name
        )


class CollectionPermission(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, null=False)
    collection = models.ForeignKey(Collection, null=False)

    can_write = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'collection')

apps/composition/views.py
import json
from django.conf import settings

from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import DetailView, TemplateView

from badgeuser.serializers import UserProfileField
from mainsite.utils import installed_apps_list

from .models import Collection, LocalBadgeInstance
from .serializers import CollectionSerializer, LocalBadgeInstanceUploadSerializer


class EarnerPortal(TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        """
        Pass initial data to a view template so that the React.js front end can
        render.
        """
        context = super(EarnerPortal, self).get_context_data(**kwargs)

        user_collections = CollectionSerializer(
            Collection.objects.filter(owner=self.request.user),
            many=True).data

        user_badges = LocalBadgeInstanceUploadSerializer(
            LocalBadgeInstance.objects.filter(recipient_user=self.request.user),
            many=True).data

        context.update({
            'initial_data': json.dumps({
                'earner_collections': user_collections,
                'earner_badges': user_badges,
                'installed_apps': installed_apps_list(),
                'user': UserProfileField(self.request.user, context=kwargs).data,
                'STATIC_URL': settings.STATIC_URL
            }),
        })

        return context


class CollectionDetailView(DetailView):
    model = Collection
    context_object_name = 'collection'

    @method_decorator(xframe_options_exempt)
    def get(self, request, *args, **kwargs):
        response = super(CollectionDetailView, self).get(request, *args, **kwargs)

        if self.object.share_hash == '' or \
                self.object.share_hash != kwargs.get('share_hash'):
            return HttpResponse(
                'Unauthorized: Invalid share URL for this collection',
                status=401
            )
        return response

    def get_context_data(self, *args, **kwargs):
        context = super(CollectionDetailView, self).get_context_data(*args, **kwargs)

        context.update({
        })
        return context


class CollectionDetailEmbedView(CollectionDetailView):
    template_name = 'composition/collection_detail_embed.html'

    @method_decorator(xframe_options_exempt)
    def get(self, request, *args, **kwargs):
        return super(CollectionDetailEmbedView, self).get(request, *args, **kwargs)

breakdown/templates/composition/base.html
{% load url from future %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <title>{% block head_title %}Badgr{% endblock %}</title>
  <link rel="shortcut icon" href="{{STATIC_URL}}favicon.png" />
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <link rel="stylesheet" media="screen" type="text/css" href="{{STATIC_URL}}css/bootstrap/css/bootstrap.css">

  <!-- main stylesheet -->
  <link rel="stylesheet" media="screen" type="text/css" href="{{STATIC_URL}}css/screen.css">

  {% block extrastyle %}{% endblock %}

  {% block extrahead %}{% endblock %}

  {% endblock %}
  {% if PINGDOM_MONITORING_ID %}
    {% include 'pingdom/embded.html' %}
  {% endif %}
</head>
<body class="{% block bodyclass %}accounts{% endblock %}">
  

  {% block pre_content %}

    {% if messages %}
      <div class="accounts-panel messages">
      {% for message in messages %}
        <div class="alert alert-info" role="alert">
          {{message}}
        </div>
      {% endfor %}
      </div>
    {% endif %}

  {% endblock %}

  <div class="accounts-panel container-fluid">
  {% block content %}

      <ul class="user-actions nav nav-pills">
      {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change email</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
      {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
      {% endif %}
      </ul>

  {% endblock %}
  </div>

</body>
</html>

breakdown/templates/composition/collection_detail.html
{% extends "base_interior.html" %}

{% set page_title="Collection" %}

{% block content %}		
    <div class="wrapper main-app-container">
        <header class="main-header">
            <div class="wrap">
                <div class="navbar navbar-default navbar-static-top">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">
                            <span>Badgr</span>
                        </a>
                    </div>
                </div>
            </div>
        </header>

        <div class="main-section content-container">
            <div class="wrap page-wrapper">
                <div class="main-component clearfix">
                    <div class="action-bar clearfix">
                        <div class="main-component-content-title col-xs-12">
                            <h3>{{collection.name}}</h3>
                        </div>
                    </div>
                    <p class="collection-owner">Badges earned by {{collection.owner.get_full_name()}}</p>
                    <p class="collection-description">{{collection.description}}</p>

                    <div class="collection-badges-list container-fluid">
                    {% for instance in collection.instances.all() %}
                        {% set metadata = instance.localbadgeinstancecollection_set.get(collection=collection) %}
                        <div class="row badge-display badge-display-full col-xs-12">
                            <div class="row col-xs-12">
                                <h1>{{instance.json.get('badge').get('name')}}</h1>
                            </div>
                            <div class="row">
                                <div class="col-xs-4">
                                    <img src="{{instance.image.url}}" />
                                </div>
                                <div class="col-xs-8">
                                    <p>
                                        <label>Description:</label>
                                        <span>{{ instance.json.get('badge').get('description') }}</span>
                                    </p>
                                    <p>
                                        <label>Criteria:</label>
                                        <span><a href="{{instance.json.get('badge').get('criteria')}}">{{instance.json.get('badge').get('criteria')}}</a></span>
                                    </p>
                                    <p>
                                        <label>Issuer:</label>
                                        <span><a href="{{instance.json.get('badge').get('issuer').get('url')}}">{{instance.json.get('badge').get('issuer').get('name')}}</a></span>
                                    </p>

                                  
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">

                                    <p>
                                        <label>Recipient identifier:</label>
                                        <span>{{instance.recipient_identifier}}</span>
                                    </p>
                                    {% if metadata.description %}
                                    <p>
                                        <label>Earner's description:</label>
                                        <span>{{metadata.description}}</span>
                                    </p>
                                    {% endif %}
                                </div>
                            </div>
                            
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

breakdown/templates/composition/collection_detail_embed.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>{% block head_title %}Badgr{% endblock %}</title>
    <link rel="shortcut icon" href="{{STATIC_URL}}favicon.png" />
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" media="screen" type="text/css" href="{{STATIC_URL}}css/bootstrap/css/bootstrap.css">

    <!-- main stylesheet -->
    <link rel="stylesheet" media="screen" type="text/css" href="{{STATIC_URL}}css/screen.css">

    {% block extrastyle %}{% endblock %}

    {% block extrahead %}{% endblock %}

    {% endblock %}
    <base target="_parent" />
</head>
<body class="badgr embedded-body">

  <div class="iframe-embed-container">
    <div class="wrapper main-app-container">
        <header class="main-header">
            <div class="wrap">
                <div class="navbar navbar-default navbar-static-top">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="https://badgr.io">
                            <span>Badgr</span>
                        </a>
                    </div>
                </div>
            </div>
        </header>

        <div class="main-section content-container">
            <div class="wrap page-wrapper">
                <div class="main-component clearfix">
                    <div class="action-bar clearfix">
                        <div class="main-component-content-title col-xs-12">
                            <h4><a href="{{collection.share_url}}">{{collection.name}}</a></h4>
                        </div>
                    </div>
                    <p class="collection-owner">Badges earned by {{collection.owner.get_full_name()}}</p>
                    <p class="collection-description">{{collection.description}}</p>

                    <div class="collection-badges-list container-fluid">
                    {% for instance in collection.instances.all() %}
                        {% set metadata = instance.localbadgeinstancecollection_set.get(collection=collection) %}
                        <div class="row badge-display badge-display-full col-xs-12">
                            <div class="row col-xs-12">
                                <h1>{{instance.json.get('badge').get('name')}}</h1>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="col-embed-6">
                                        <img src="{{instance.image.url}}" />
                                    </div>
                                    <p>
                                        <label>Description:</label>
                                        <span>{{ instance.json.get('badge').get('description') }}</span>
                                    </p>
                                    <p>
                                        <label>Criteria:</label>
                                        <span><a href="{{instance.json.get('badge').get('criteria')}}">{{instance.json.get('badge').get('criteria')}}</a></span>
                                    </p>
                                    <p>
                                        <label>Issuer:</label>
                                        <span><a href="{{instance.json.get('badge').get('issuer').get('url')}}">{{instance.json.get('badge').get('issuer').get('name')}}</a></span>
                                    </p>

                                  
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">

                                    <p>
                                        <label>Recipient identifier:</label>
                                        <span>{{instance.recipient_identifier}}</span>
                                    </p>
                                    {% if metadata.description %}
                                    <p>
                                        <label>Earner's description:</label>
                                        <span>{{metadata.description}}</span>
                                    </p>
                                    {% endif %}
                                </div>
                            </div>
                            
                        </div>
                    {% endfor %}
                    </div>
                    <p class="embed-info">This badge collection verified by <a href="https://badgr.io">Badgr</a>. <a href="{{collection.share_url}}">View details</a>.</p>
                </div>
            </div>
        </div>
    </div>
  </div>

</body>
</html>