apps/health/urls.py
from django.conf.urls import patterns, url
from views import health

urlpatterns = patterns('contact.views',
    url(r'^$', health, name='server_health'),
)

apps/mainsite/urls.py
from django.apps import apps
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from rest_framework.authtoken.views import obtain_auth_token

from .views import SitemapView, info_view, email_unsubscribe

from mainsite.admin import badgr_admin
badgr_admin.autodiscover()
# make sure that any view/model/form imports occur AFTER admin.autodiscover

TOKEN_REGEX = '(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})'

sitemaps = {
}

urlpatterns = patterns('',
    # Backup URLs in case the server isn't serving these directly
    url(r'^favicon\.png[/]?$', RedirectView.as_view(url='%simages/favicon.png' % settings.STATIC_URL)),
    url(r'^favicon\.ico[/]?$', RedirectView.as_view(url='%simages/favicon.png' % settings.STATIC_URL)),
    url(r'^robots\.txt$', RedirectView.as_view(url='%srobots.txt' % settings.STATIC_URL)),

    # Home
    url(r'^$', info_view, name='index'),

    # Sitemaps
    url(r'^sitemap$', SitemapView.as_view(), name='sitemap'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Admin URLs
    url(r'^staff/', include(badgr_admin.urls)),

    # accounts:
    url(r'^accounts[/]?$', RedirectView.as_view(url='/accounts/email/')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^unsubscribe/(?P<email_encoded>[^/]+)/(?P<expiration>[^/]+)/(?P<signature>[^/]+)', email_unsubscribe, name='unsubscribe'),
    url(r'^login', RedirectView.as_view(url='/accounts/login', permanent=False, query_string=True), name='login'),
    url(r'^logout', RedirectView.as_view(url='/accounts/logout', permanent=False), name='logout'),

    # REST Framework-based APIs
    url(r'^user', include('badgeuser.urls')),
    url(r'^v1/user', include('badgeuser.api_urls')),
    url(r'^api-auth/token$', obtain_auth_token),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^public', include('issuer.public_api_urls')),

    url(r'^docs/', include('rest_framework_swagger.urls')),

    # Service health endpoint
    url(r'^health', include('health.urls')),

    # JSON-LD Context
    url(r'^json-ld/', include('badgrlog.urls')),

)

if apps.is_installed('issuer'):
    urlpatterns += patterns('',
        url(r'^v1/$', RedirectView.as_view(url='/v1/issuer/issuers', permanent=False)),
        url(r'^v1/issuer', include('issuer.api_urls')),
        url(r'^issuer', include('issuer.urls')),
    )

if apps.is_installed('composition'):
    urlpatterns += patterns('',
        url(r'^v1/earner', include('composition.api_urls')),
        url(r'^earner', include('composition.urls')),
    )

if apps.is_installed('badgebook'):
    urlpatterns += patterns('',
        url(r'^v1/badgebook', include('badgebook.api_urls')),
        url(r'^badgebook', include('badgebook.urls')),
    )


handler404 = 'mainsite.views.error404'
handler500 = 'mainsite.views.error500'
# Test URLs to allow you to see these pages while DEBUG is True
if getattr(settings, 'DEBUG_ERRORS', False):
    urlpatterns = patterns('mainsite.views',
        url(r'^error/404/$', 'error404', name='404'),
        url(r'^error/500/$', 'error500', name='500'),
    ) + urlpatterns

# If DEBUG_MEDIA is set, have django serve anything in MEDIA_ROOT at MEDIA_URL
if getattr(settings, 'DEBUG_MEDIA', True):
    media_url = getattr(settings, 'MEDIA_URL', '/media/').lstrip('/')
    urlpatterns = patterns('',
        url(r'^%s(?P<path>.*)$' % (media_url,), 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT
        }),
    ) + urlpatterns

# If DEBUG_STATIC is set, have django serve up static files even if DEBUG=False
if getattr(settings, 'DEBUG_STATIC', True):
    static_url = getattr(settings, 'STATIC_URL', '/static/').lstrip('/')
    urlpatterns = patterns('',
        url(r'^%s(?P<path>.*)' % (static_url,), 'django.contrib.staticfiles.views.serve', kwargs={
            'insecure': True,
        })
    ) + urlpatterns

# Serve pattern library view only in debug mode or if explicitly declared
if getattr(settings, 'DEBUG', True) or getattr(settings, 'SERVE_PATTERN_LIBRARY', False):
    urlpatterns = patterns('',
       url(r'^component-library$', TemplateView.as_view(template_name='component-library.html'), name='component-library')
    ) + urlpatterns

apps/composer/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from autoslug import AutoSlugField
import cachemodel

from credential_store.models import StoredBadgeInstance

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

######
#
# !!! This app and all its models have been deprecated !!!
# see the new 'composition' app
#
#####


class Collection(cachemodel.CacheModel):
    name = models.CharField(max_length=128)
    slug = AutoSlugField(
        max_length=128, populate_from='name',
        blank=False, editable=True
    )
    description = models.CharField(max_length=255, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, related_name="composer_collection_set")
    share_hash = models.CharField(max_length=255, null=False, blank=True)

    instances = models.ManyToManyField(
        StoredBadgeInstance, through='StoredBadgeInstanceCollection'
    )
    shared_with = models.ManyToManyField(
        AUTH_USER_MODEL, through='CollectionPermission', related_name='composer_shared_with_me'
    )

    class Meta:
        unique_together = ('owner', 'slug')

    @property
    def share_url(self):
        if self.share_hash != '':
            return getattr(settings, 'HTTP_ORIGIN') + reverse(
                'shared_collection',
                args=[self.pk, self.share_hash]
            )
        return ''


class StoredBadgeInstanceCollection(models.Model):
    instance = models.ForeignKey(StoredBadgeInstance, null=False)
    collection = models.ForeignKey(Collection, null=False)

    description = models.TextField(blank=True)

    class Meta:
        unique_together = ('instance', 'collection')


class CollectionPermission(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, null=False, related_name="composer_collectionpermission_set")
    collection = models.ForeignKey(Collection, null=False)

    can_write = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'collection')

breakdown/templates/certificates/certificate_detail.html
{% extends "base_interior.html" %}


{% set page_title="Print Badge Certificate" %}


{% block content %}
	
	{% if badge_image %}
		<img src="{{badge_image}}" alt="Badge Image for {{badge_name}}" />
	{% endif %}
	{% if qrcode and baked_image_url %}
		<a href="{{baked_image_url}}"><img src="{{qrcode}}" alt="You can scan this to download the baked badge image to your device." /></a>
	{% endif %}

	{% if badge_name %}
		<h2> {{badge_name}} </h2>
	{% endif %}

	{% if badge_description %}
		<p> Description: {{badge_description}} </p>
	{% endif %}	

	{% if badge_issuer and issuer_url %}
		<p> Issuer: <a href="{{issuer_url}}">{{badge_issuer}}</a> </p>
	{% endif %}	

	{% if badge_recipient and issue_date %}
		<p>Issued to {{badge_recipient}} on {{issue_date}} </p>
	{% endif %}	

{% endblock %}

breakdown/templates/certificates/certificate_form.html
{% extends "base_interior.html" %}


{% set page_title="Create a certificate" %}


{% block content %}		
	<div class="content_area">	
		{{snippet('create-certificate-intro')|default('<p>Please submit the form below to generate your certificate.</p>', true)|safe}}
		<form class="contact" action="" method="post" enctype='multipart/form-data'>
			<fieldset>
				<ol>
				{% for field in form %}
					<li>
						<label for="id_name">{{field.label}}</label>
						{% if field.errors %}
							<span class="error">{{field.errors|safe}}</span>
						{% endif %}
						{{field|safe}}
					</li>
				{% endfor %}
				</ol>
				{{ csrf() }}
			</fieldset>
			
			<fieldset>
				<ol>
					<li>
						<button type="submit">Send</button>
					</li>
				</ol>
			</fieldset>
		</form>
	</div>

{% endblock %}